server.port=8084
spring.application.name=attempt-service

# MongoDB Atlas (cloud)
spring.data.mongodb.uri=mongodb+srv://yadneshumredkar7_db_user:57s9oPSkGcAGUtYH@cluster0.h5s2irr.mongodb.net/attempt_db

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/